Updated readme action version.
clouddrove/terraform-aws-security-group pull request #41
Opened 2023-10-02 17:43 UTC by d4kverma

## what
* Updated readme action to latest version. 

## why
* to use latest version on worflow

2023-10-02 17:48 UTC, themaniskshah approved these changes, later dismissed

2023-10-02 17:50 UTC, nileshgadgi requested changes
there are tflint warnings. 😄

2023-10-03 09:14 UTC, themaniskshah approved these changes

2023-10-03 09:23 UTC, nileshgadgi approved these changes
LGTM!

2023-10-04 14:39 UTC, closed without merging